---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-certificates
  namespace: default
spec:
  isCA: true
  commonName: elastic-certificates
  secretName: elastic-certificates
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
    - elasticsearch-master
    - elasticsearch-master.default.svc
    - elasticsearch-master.default.svc.cluster.local
