apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-instance
spec:
  version: 8.16.0
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  http:
    tls:
      certificate:
        secretName: elasticsearch-cert
