services:
  redis:
    image: redis:alpine
    hostname: redis-compose
    ports:
      - "6379:6379"
  rdb:
    image: mysql:latest
    hostname: mysql-compose
    restart: always
    ports: 
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: "read_this_you_bot"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d
  mongo:
    image: mongo
    hostname: mongo-compose
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test
  elastic:
    image: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD=test
  basic-backend:
    depends_on:
      - redis
      - mongo
    build: ./basic-backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
      - PORT=3001
      - MONGODB_URL=mongodb://root:test@mongo-compose:27017/log
  workload-handler:
    depends_on:
      - rdb
      - redis
      - mongo
    build: ./workload-handler
    ports:
      - "3011:3011"
    environment:
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
      - PORT=3011
      - RDB_HOST=mysql-compose
      - RDB_PORT=3306
      - MONGODB_URL=mongodb://root:test@mongo-compose:27017/log
 