services:
  redis:
    image: redis:alpine
    hostname: redis-compose
  rdb:
    image: mysql:latest
    hostname: mysql-compose
    restart: always
    ports: 
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: "read_this_you_bot"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d
  basic-backend:
    depends_on:
      - redis
    build: ./basic-backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
      - PORT=3001
  workload-handler:
    depends_on:
      - rdb
      - redis
    build: ./workload-handler
    ports:
      - "3011:3011"
    environment:
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
      - PORT=3011
      - RDB_HOST=mysql-compose
      - RDB_PORT=3306
 