services:
  redis:
    image: redis:alpine
    hostname: redis-compose
  backend:
    build: ./basic-backend
    ports:
      - "3000:3000"
  workload-handler:
    build: ./workload-handler
    ports:
      - "3010:3010"
