from datetime import datetime, timezone
from typing import Any

def get_mock_topology(region: str) -> dict[str, Any]:
    resources = [
        {
            "id": "vpc-001",
            "type": "vpc",
            "name": "main-vpc",
            "region": region,
            "layer": "basis",
            "parentId": None,
            "metadata": {"cidr": "10.0.0.0/16", "state": "available"},
        },
        {
            "id": "igw-001",
            "type": "internet_gateway",
            "name": "main-igw",
            "region": region,
            "layer": "basis",
            "parentId": "vpc-001",
            "metadata": {"state": "attached"},
        },
        {
            "id": "sg-001",
            "type": "security_group",
            "name": "web-sg",
            "region": region,
            "layer": "basis",
            "parentId": "vpc-001",
            "metadata": {"inbound": "80,443,22", "outbound": "all"},
        },
        {
            "id": "sg-002",
            "type": "security_group",
            "name": "db-sg",
            "region": region,
            "layer": "basis",
            "parentId": "vpc-001",
            "metadata": {"inbound": "5432", "outbound": "all"},
        },
        {
            "id": "subnet-pub-1",
            "type": "subnet",
            "name": "public-subnet-1a",
            "region": region,
            "layer": "basis",
            "parentId": "vpc-001",
            "metadata": {"cidr": "10.0.1.0/24", "az": f"{region}a", "type": "public"},
        },
        {
            "id": "subnet-pub-2",
            "type": "subnet",
            "name": "public-subnet-1c",
            "region": region,
            "layer": "basis",
            "parentId": "vpc-001",
            "metadata": {"cidr": "10.0.2.0/24", "az": f"{region}c", "type": "public"},
        },
        {
            "id": "subnet-priv-1",
            "type": "subnet",
            "name": "private-subnet-1a",
            "region": region,
            "layer": "basis",
            "parentId": "vpc-001",
            "metadata": {"cidr": "10.0.11.0/24", "az": f"{region}a", "type": "private"},
        },
        {
            "id": "subnet-priv-2",
            "type": "subnet",
            "name": "private-subnet-1c",
            "region": region,
            "layer": "basis",
            "parentId": "vpc-001",
            "metadata": {"cidr": "10.0.12.0/24", "az": f"{region}c", "type": "private"},
        },
        {
            "id": "alb-001",
            "type": "alb",
            "name": "web-alb",
            "region": region,
            "layer": "compute",
            "parentId": "subnet-pub-1",
            "metadata": {"dns": "web-alb.elb.amazonaws.com", "scheme": "internet-facing"},
        },
        {
            "id": "ec2-001",
            "type": "ec2",
            "name": "web-server-1a",
            "region": region,
            "layer": "compute",
            "parentId": "subnet-priv-1",
            "metadata": {"instance_type": "t3.medium", "state": "running", "private_ip": "10.0.11.10"},
        },
        {
            "id": "ec2-002",
            "type": "ec2",
            "name": "web-server-1c",
            "region": region,
            "layer": "compute",
            "parentId": "subnet-priv-2",
            "metadata": {"instance_type": "t3.medium", "state": "running", "private_ip": "10.0.12.10"},
        },
        {
            "id": "rds-001",
            "type": "rds",
            "name": "main-postgres",
            "region": region,
            "layer": "compute",
            "parentId": "subnet-priv-1",
            "metadata": {"engine": "postgres", "version": "15.4", "instance_class": "db.t3.medium", "status": "available"},
        },
    ]

    return {
        "resources": resources,
        "region": region,
        "fetchedAt": datetime.now(timezone.utc).isoformat(),
    }
