apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-backend
  namespace: barnacle
  labels:
    app: basic-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-backend
  template:
    metadata:
      labels:
        app: basic-backend
    spec:
      containers:
      - name: basic-backend
        image: innfi/basic-backend:latest
        ports:
          - containerPort: 3000
            protocol: TCP
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: PORT
            value: "3000"
          - name: ES_URL
            value: "elasticsearch-cluster.default.svc.cluster.local"
          - name: ELASIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-cluster-es-elastic-user
                key: elastic
          - name: CA_PATH
            value: "fixme"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-backend
  namespace: barnacle
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020
  selector:
    app: basic-backend
