apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-handler
  namespace: barnacle
  labels:
    app: workload-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-handler
  template:
    metadata:
      labels:
        app: workload-handler
    spec:
      containers:
      - name: workload-handler
        image: innfi/workload-handler:latest
        ports:
          - containerPort: 3010
            protocol: TCP
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: PORT
            value: "3010"
          - name: RDB_HOST
            value: "mysql"
          - name: RDB_PORT
            value: "3306"
          - name: RDB_USERNAME
            value: "root"
          - name: RDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
          - name: ES_URL
            value: "elasticsearch-cluster.default.svc.cluster.local"
          - name: ELASIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-cluster-es-elastic-user
                key: elastic
          - name: CA_PATH
            value: "fixme"
---
apiVersion: v1
kind: Service
metadata:
  name: workload-handler
  namespace: barnacle
spec:
  type: ClusterIP
  selector:
    app: workload-handler
  ports:
    - port: 3010
