include:
  - elastic.yaml
  - persistence.yaml

services:
  basic-backend:
    depends_on:
      - redis
      - es01
    build: ./basic-backend
    ports:
      - "3001:3001"
    volumes:
      - certs:/certs
    environment:
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
      - PORT=3001
      - ES_URL=https://es01:9200
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - CA_PATH=/certs/ca/ca.crt
