apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-instance
#  namespace: elasticsearch
spec:
  version: 8.16.0
  count: 1
  elasticsearchRef:
    name: barnacle
#    namespace: elasticsearch
  http:
    tls:
      certificate:
        secretName: barnacle-es-cert
