name: basic-backend workflow
on:
  push:
    paths:
      - '.github/workflows/action.basic-backend.yaml'
      - 'basic-backend/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./basic-backend/
    steps:
      - name: baseline
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: './basic-backend/'

      - name: build
        run: npm run build

  docker:
    name: docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./basic-backend
    steps:
      - name: docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          file: ./basic-backend/Dockerfile
          context: ./basic-backend
          push: true
          tags:  innfi/basic-backend:latest


