name: workload-handler action
on:
  push:
    paths:
      - '.github/workflows/action.workload-handler.yaml'
      - 'workload-handler/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workload-handler/
    steps:
      - name: baseline
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: './workload-handler/'

      - name: install
        run: npm install

      - name: build
        run: npm run build

  docker:
    name: docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workload-handler
    steps:
      - name: docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:workload-handler"
          push: true
          tags:  innfi/workload-handler:latest
